# Generated by Django 2.2.6 on 2021-05-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guessnumbers',
            old_name='num_lotto',
            new_name='num_lottos',
        ),
    ]
